=== anirul/SeeMark/fattycurd-sub-menu.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">
	
	<xs:annotation>
		<xs:documentation xml:lang="en">
			DroneWar sub menu description
			author : Frederic DUBOUCHET
			e-mail : angel@calodox.org
		</xs:documentation>
	</xs:annotation>
	
	<!-- some basic types -->
	<xs:simpleType name="note-type">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>
	<xs:complexType name="position-type">
		<xs:attribute name="hpos" type="xs:float" use="required"/>
		<xs:attribute name="vpos" type="xs:float" use="required"/>
	</xs:complexType>
	<xs:complexType name="size-type">
		<xs:attribute name="height" type="xs:float" use="required"/>
		<xs:attribute name="width" type="xs:float" use="required"/>
	</xs:complexType>
	<xs:simpleType name="location-type">
		<xs:restriction base="xs:anyURI"/>
	</xs:simpleType>
	<xs:complexType name="item-type">
		<xs:attribute name="name" type="xs:string"/>
		<xs:attribute name="value" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="game-logic-type">
		<xs:all>
			<xs:element name="location" type="location-type" />
		</xs:all>
	</xs:complexType>
	
	<!-- SET-VALUE-TYPE -->
	<xs:complexType name="set-value-type">
		<xs:attribute name="linked-to" type="xs:string" use="required"/>
		<xs:attribute name="value" type="xs:string" use="required"/>
	</xs:complexType>
	
	<!-- IMAGE-TYPE -->
	<xs:complexType name="image-type">
		<xs:sequence>
			<xs:element name="position" type="position-type" minOccurs="1" maxOccurs="1"/>
			<xs:element name="size" type="size-type" minOccurs="1" maxOccurs="1"/>
			<xs:element name="image" type="location-type" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="coordinate">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="absolute"/>
					<xs:enumeration value="relative"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	
	<!-- BUTTON-TYPE -->
	<xs:complexType name="button-type">
		<xs:sequence>
			<xs:element name="position" type="position-type" minOccurs="1" maxOccurs="1"/>
			<xs:element name="size" type="size-type" minOccurs="1" maxOccurs="1"/>
			<xs:element name="image-up" type="location-type" minOccurs="1" maxOccurs="1"/>
			<xs:element name="image-flyby" type="location-type" minOccurs="1" maxOccurs="1"/>
			<xs:element name="image-down" type="location-type" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="goto-state" type="xs:string" use="required"/>
		<xs:attribute name="coordinate">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="absolute"/>
					<xs:enumeration value="relative"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	
	<!-- TOGGLE-BUTTON-TYPE-->
	<xs:complexType name="toggle-button-type">
		<xs:sequence>
			<xs:element name="position" type="position-type" minOccurs="1" maxOccurs="1"/>
			<xs:element name="size" type="size-type" minOccurs="1" maxOccurs="1"/>
			<xs:element name="image-up" type="location-type" minOccurs="1" maxOccurs="1"/>
			<xs:element name="image-down" type="location-type" minOccurs="1" maxOccurs="1"/>
			<xs:element name="image-up-flyby" type="location-type" minOccurs="1" maxOccurs="1"/>
			<xs:element name="image-down-flyby" type="location-type" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="linked-to" type="xs:string" use="required"/>
		<xs:attribute name="value" type="xs:string" use="required"/>
		<xs:attribute name="coordinate">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="absolute"/>
					<xs:enumeration value="relative"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	
	<!-- IRR-BUTTON-TYPE -->
	<xs:complexType name="irr-button-type">
		<xs:sequence>
			<xs:element name="position" type="position-type" minOccurs="1" maxOccurs="1"/>
			<xs:element name="size" type="size-type" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="text" type="xs:string" use="required"/>
		<xs:attribute name="tooltip" type="xs:string"/>
		<xs:attribute name="goto-state" type="xs:string" use="required"/>
		<xs:attribute name="coordinate">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="absolute"/>
					<xs:enumeration value="relative"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	
	<!-- IRR-TEXT-TYPE -->
	<xs:complexType name="irr-text-type">
		<xs:all>
			<xs:element name="position" type="position-type" />
			<xs:element name="size" type="size-type" />
		</xs:all>
		<xs:attribute name="coordinate">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="absolute"/>
					<xs:enumeration value="relative"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="linked-to" type="xs:string" use="required"/>
		<xs:attribute name="text" type="xs:string"/>
	</xs:complexType>
	
	<!-- IRR-LABEL-TYPE -->
	<xs:complexType name="irr-label-type">
		<xs:sequence>
			<xs:element name="position" type="position-type" minOccurs="1" maxOccurs="1"/>
			<xs:element name="size" type="size-type" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="coordinate">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="absolute"/>
					<xs:enumeration value="relative"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="text" type="xs:string"/>
		<xs:attribute name="linked-to" type="xs:string"/>
	</xs:complexType>
	
	<!-- IRR-SLIDER-TYPE -->
	<xs:complexType name="irr-slider-type">
		<xs:sequence>
			<xs:element name="position" type="position-type" minOccurs="1" maxOccurs="1"/>
			<xs:element name="size" type="size-type" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="coordinate">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="absolute"/>
					<xs:enumeration value="relative"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="init" type="xs:integer" use="required"/>
		<xs:attribute name="linked-to" type="xs:string" use="required"/>
	</xs:complexType>
	
	<!-- IRR-COMBO-TYPE -->
	<xs:complexType name="irr-combo-type">
		<xs:sequence>
			<xs:element name="position" type="position-type" minOccurs="1" maxOccurs="1"/>
			<xs:element name="size" type="size-type" minOccurs="1" maxOccurs="1"/>
			<xs:element name="item" type="item-type" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="coordinate">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="absolute"/>
					<xs:enumeration value="relative"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="init" type="xs:string"/>
		<xs:attribute name="linked-to" type="xs:string" use="required"/>
	</xs:complexType>
	
	<!-- GUI-STATE-TYPE -->
	<xs:complexType name="gui-state-type">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="set-value" type="set-value-type" />
			<xs:element name="image" type="image-type" />
			<xs:element name="button" type="button-type" />
			<xs:element name="toggle-button" type="toggle-button-type" />
			<xs:element name="irr-button" type="irr-button-type" />
			<xs:element name="irr-text" type="irr-text-type" />
			<xs:element name="irr-label" type="irr-label-type" />
			<xs:element name="irr-combo" type="irr-combo-type" />
			<xs:element name="irr-slider" type="irr-slider-type" />
		</xs:choice>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="timeout" type="xs:float"/>
		<xs:attribute name="goto-state" type="xs:string" use="required"/>
	</xs:complexType>
	
	<!-- STILL-STATE-TYPE -->
	<xs:complexType name="still-state-type">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="set-value" type="set-value-type" />
			<xs:element name="image" type="image-type" />
			<xs:element name="irr-label" type="irr-label-type" />
		</xs:choice>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="timeout" type="xs:float"/>
		<xs:attribute name="goto-state" type="xs:string" use="required"/>
	</xs:complexType>
	
	<!-- GAME-STATE-TYPE -->
	<xs:complexType name="game-state-type">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="set-value" type="set-value-type" />
			<xs:element name="image" type="image-type" />
			<xs:element name="irr-button" type="irr-button-type" />
			<xs:element name="irr-text" type="irr-text-type" />
			<xs:element name="irr-label" type="irr-label-type" />
			<xs:element name="irr-combo" type="irr-combo-type" />
			<xs:element name="irr-slider" type="irr-slider-type" />
			<xs:element name="button" type="button-type" />
			<xs:element name="toggle-button" type="toggle-button-type" />
		</xs:choice>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="linked-to" type="xs:string" use="required"/>
		<xs:attribute name="victory-on" type="xs:string" use="required"/>
		<xs:attribute name="defeat-on" type="xs:string" use="required"/>
		<xs:attribute name="goto-state-victory" type="xs:string" use="required"/>
		<xs:attribute name="goto-state-defeat" type="xs:string" use="required"/>
		<xs:attribute name="logic" type="xs:string" use="required"/>
	</xs:complexType>
	
	<xs:element name="sub-menu">
		<xs:complexType>
			<xs:choice>
				<xs:element name="still-state" type="still-state-type" />
				<xs:element name="gui-state" type="gui-state-type" />
				<xs:element name="game-state" type="game-state-type" />
			</xs:choice>
		</xs:complexType>
	</xs:element>
	
</xs:schema>

=== anirul/SeeMark/gui_logo_kwakwa.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
 FATTYCURD MENU CONFIG
 
 Resolution can be either absolute or relative if absolute then if the user
 change resolution the objects will be missplaces! Relative positionning and
 size express in part of fullscreen resolution
 
 0.0, 0.0        0.0, 1.0
 screen
 1.0, 0.0        1.0, 1.0
 
 Don't forget in case you use relative positionning to also specify the size
 or it won't be correct!
 
 FAQ
 [Position] express the position of the CENTER of the object!
 [timeout] floating value in second
 [set-value] is a value that is send to the game engine
 [linked-to] this value is linked to a value in the game engine
 -->
<sub-menu
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="fattycurd-sub-menu.xsd">
	<still-state name="kwakwa_logo" goto-state="dorian_logo" timeout="3.0">

		<set-value linked-to="fattycurd.camera" value="fixed"/>
		
		<trigger linked-to="sound_kwakwa" />

		<image coordinate="relative">
			<position hpos="0.5" vpos="0.5"/>
			<size width="1.0" height="1.0"/>
			<location>Images/white.png</location>
		</image>

        <image coordinate="relative">
			<position hpos="0.5" vpos="0.5"/>
			<location>Images/kwakwa.png</location>
		</image>
	</still-state>
</sub-menu>

=== anirul/SeeMark/gui_title.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
 FATTYCURD MENU CONFIG
 
 Resolution can be either absolute or relative if absolute then if the user
 change resolution the objects will be missplaces! Relative positionning and
 size express in part of fullscreen resolution
 
 0.0, 0.0        0.0, 1.0
 screen
 1.0, 0.0        1.0, 1.0
 
 Don't forget in case you use relative positionning to also specify the size
 or it won't be correct!
 
 FAQ
 [Position] express the position of the CENTER of the object!
 [timeout] floating value in second
 [set-value] is a value that is send to the game engine
 [linked-to] this value is linked to a value in the game engine
 -->
<sub-menu
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="fattycurd-sub-menu.xsd">
	<still-state name="title" goto-state="game" timeout="10.0">

		<set-value linked-to="fattycurd.camera" value="fixed"/>
				
        <image coordinate="relative">
            <position hpos="0.5" vpos="0.5"/>
            <size height="1.0" width="1.2"/>
            <location>Images/Title_ScreenBG.jpg</location>
        </image>
		
        <image coordinate="relative">
			<position hpos="0.5" vpos="0.5"/>
			<size height="0.4" width="0.8"/>
			<location>Images/title.png</location>
		</image>
	</still-state>
</sub-menu>
